import test from 'node:test';
import assert from 'node:assert/strict';
import { createHandler, projectAggregate, OWNER } from '../supabase/functions/internal-telemetry-dashboard/handler.mjs';
const empty = {days:30,activity:{active_installations:0,new_installations:0},daily:[],versions:[],versions_truncated:false,endpoints:{reporting_installations:0,endpoint_reach:0,median:null,p95:null},sources:[],quality:{missing_counts:0,uncertain_counts:0,suspicious_versions:0}};
const owner={email:OWNER,email_confirmed_at:'2026-01-01'};
function setup(user=owner, data=empty){let queries=0;const handler=createHandler({authenticate:async token=>token==='valid'?user:null,aggregate:async()=>{queries++;return data;},now:()=> '2026-09-14T00:00:00.000Z'});return {handler,queries:()=>queries};}
function req(token='valid',body={days:30},origin='https://ce-deploy.voipnorm.com'){return new Request('https://example.test',{method:'POST',headers:{...(token?{Authorization:`Bearer ${token}`} : {}),Origin:origin},body:JSON.stringify(body)});}
for(const token of [null,'invalid','expired','service_role'])test(`401: ${token ?? 'missing'} credential`,async()=>{const s=setup();assert.equal((await s.handler(req(token))).status,401);assert.equal(s.queries(),0);});
for(const user of [{email:'other@example.com',email_confirmed_at:'x'},{email:OWNER},{...owner,is_anonymous:true},{email:'other@example.com',email_confirmed_at:'x',user_metadata:{email:OWNER}}])test(`403: only confirmed non-anonymous owner ${JSON.stringify(user)}`,async()=>{const s=setup(user);assert.equal((await s.handler(req())).status,403);assert.equal(s.queries(),0);});
test('authorized owner gets valid empty aggregate with no-store',async()=>{const s=setup();const r=await s.handler(req());assert.equal(r.status,200);assert.equal(r.headers.get('Cache-Control'),'private, no-store');assert.equal((await r.json()).endpoints.median,null);assert.equal(s.queries(),1);});
test('untrusted origin has no CORS permission and no query',async()=>{const s=setup();const r=await s.handler(req('valid',{},'https://evil.example'));assert.equal(r.status,403);assert.equal(r.headers.get('Access-Control-Allow-Origin'),null);assert.equal(s.queries(),0);});
test('preflight permits only the site',async()=>{const s=setup();const r=await s.handler(new Request('https://example.test',{method:'OPTIONS',headers:{Origin:'https://ce-deploy.voipnorm.com'}}));assert.equal(r.status,204);assert.equal(s.queries(),0);});
for(const body of [{days:2},{days:30,select:'*'},null,{days:'30'},{days:30,payload:'x'.repeat(200)}])test('invalid or oversized request never queries',async()=>{const s=setup();assert.equal((await s.handler(req('valid',body))).status,400);assert.equal(s.queries(),0);});
test('privacy: unexpected raw fields are discarded at every nesting level',()=>{const data=structuredClone(empty);data.installation_id='raw-canary';data.activity.deletion_token='raw-canary';data.endpoints.ip_address='raw-canary';data.daily=[{day:'2026-09-14',heartbeats:2,installation_id:'raw-canary'}];data.versions=[{version:'16.3.7',channel:'stable',installations:2,raw:'raw-canary'}];data.sources=[{source:'cloud_inventory',confidence:'complete',installations:2,raw:'raw-canary'}];assert.ok(!JSON.stringify(projectAggregate(data,30)).includes('raw-canary'));});
test('privacy: invalid labels and unbounded response fail closed',async()=>{for(const data of [{...empty,versions:[{version:'secret-uuid',channel:'stable',installations:1}]},{...empty,sources:[{source:'secret',confidence:'complete',installations:1}]},{...empty,daily:Array(181).fill({day:'2026-09-14',heartbeats:1})}]){const s=setup(owner,data);const r=await s.handler(req());assert.equal(r.status,503);assert.deepEqual(await r.json(),{error:'dashboard_unavailable'});}});
test('database errors cannot leak details',async()=>{const h=createHandler({authenticate:async()=>owner,aggregate:async()=>{throw Error('raw secret data');}});const r=await h(req());assert.equal(r.status,503);assert.ok(!(await r.text()).includes('secret'));});
test('authentication outage fails closed without query',async()=>{let queried=false;const h=createHandler({authenticate:async()=>{throw Error();},aggregate:async()=>{queried=true;}});assert.equal((await h(req())).status,503);assert.equal(queried,false);});
test('dashboard page uses external assets compatible with restrictive CSP',async()=>{const {readFileSync}=await import('node:fs');const page=readFileSync('src/pages/admin/telemetry.astro','utf8');assert.ok(page.includes("script-src 'self'"));assert.ok(page.includes('noindex,nofollow'));assert.ok(!page.includes('unsafe-inline'));assert.ok(page.includes('/admin/telemetry.css'));});
test('all deployed release-channel enum values are accepted without relaxing validation',()=>{for(const channel of ['stable','beta','development','private-beta','public-beta']){const d={...empty,versions:[{version:'16.4.0-private-beta.1',channel,installations:1}]};assert.equal(projectAggregate(d,30).versions[0].channel,channel);}});
